version: '3.1'
services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: setdatauser
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: test_api_key
      POSTGRES_HOST: localhost
      PGDATA: /pg-data
    ports:
      - "5433:5432"
  app:
    build: .
    image: kirigaikabuto/api-key-test-api
    depends_on:
      - database
    ports:
      - "5000:5000"
    environment:
      POSTGRES_USER: setdatauser
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: test_api_key
    container_name: n50-teacher-api